# This workflow will publish all packages to NPM

name: Node.js Package

on: [workflow_dispatch]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm run publish
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.gh_token}}
